package servicecatalog

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

var (
	ErrServiceNotFound   = errors.New("service not found")
	ErrCodeAlreadyExists = errors.New("service code already exists")
)

// price is NUMERIC in the schema; the cast keeps the scan target a plain float64.
const serviceColumns = "id, code, name, description, price::double precision, estimated_time, active, created_at, updated_at"

type Repository struct {
	pool *pgxpool.Pool
}

func NewRepository(pool *pgxpool.Pool) *Repository { return &Repository{pool: pool} }

type rowScanner interface {
	Scan(dest ...any) error
}

func scanService(row rowScanner) (*Service, error) {
	var s Service
	err := row.Scan(&s.ID, &s.Code, &s.Name, &s.Description, &s.Price,
		&s.EstimatedTime, &s.Active, &s.CreatedAt, &s.UpdatedAt)
	if err != nil {
		return nil, err
	}
	return &s, nil
}

// uniqueViolation maps a duplicate code (ux_services_code) to ErrCodeAlreadyExists.
func uniqueViolation(err error) error {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "23505" {
		return ErrCodeAlreadyExists
	}
	return err
}

func (r *Repository) Create(ctx context.Context, in NewService) (*Service, error) {
	// services.code is GENERATED BY DEFAULT: the column is listed only when the
	// caller supplied a code, otherwise the identity generates it.
	query := "INSERT INTO services (name, description, price, estimated_time) VALUES ($1, $2, $3, $4) RETURNING " + serviceColumns
	args := []any{in.Name, in.Description, in.Price, in.EstimatedTime}
	if in.Code != nil {
		query = "INSERT INTO services (code, name, description, price, estimated_time) VALUES ($1, $2, $3, $4, $5) RETURNING " + serviceColumns
		args = []any{*in.Code, in.Name, in.Description, in.Price, in.EstimatedTime}
	}
	created, err := scanService(r.pool.QueryRow(ctx, query, args...))
	if err != nil {
		return nil, uniqueViolation(err)
	}
	return created, nil
}

func (r *Repository) List(ctx context.Context, filter ListFilter) ([]Service, error) {
	query := "SELECT " + serviceColumns + " FROM services"
	var args []any
	if filter.Active != nil {
		query += " WHERE active = $1"
		args = append(args, *filter.Active)
	}
	query += " ORDER BY code"

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	services := []Service{}
	for rows.Next() {
		s, err := scanService(rows)
		if err != nil {
			return nil, err
		}
		services = append(services, *s)
	}
	return services, rows.Err()
}

func (r *Repository) FindByID(ctx context.Context, id string) (*Service, error) {
	s, err := scanService(r.pool.QueryRow(ctx, "SELECT "+serviceColumns+" FROM services WHERE id = $1", id))
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrServiceNotFound
	}
	if err != nil {
		return nil, err
	}
	return s, nil
}

func (r *Repository) Update(ctx context.Context, id string, changes Changes) (*Service, error) {
	assignments := make([]string, 0, 4)
	args := make([]any, 0, 5)
	set := func(column string, value any) {
		args = append(args, value)
		assignments = append(assignments, fmt.Sprintf("%s = $%d", column, len(args)))
	}
	if changes.Name != nil {
		set("name", *changes.Name)
	}
	if changes.Description != nil {
		set("description", *changes.Description)
	}
	if changes.Price != nil {
		set("price", *changes.Price)
	}
	if changes.EstimatedTime != nil {
		set("estimated_time", *changes.EstimatedTime)
	}
	// Catalog.Update rejects an empty change set before reaching here; reading the
	// row back keeps the repository well-defined if it is called directly.
	if len(assignments) == 0 {
		return r.FindByID(ctx, id)
	}

	args = append(args, id)
	query := "UPDATE services SET " + strings.Join(assignments, ", ") +
		fmt.Sprintf(" WHERE id = $%d RETURNING ", len(args)) + serviceColumns

	s, err := scanService(r.pool.QueryRow(ctx, query, args...))
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrServiceNotFound
	}
	if err != nil {
		return nil, uniqueViolation(err)
	}
	return s, nil
}

// Deactivate is the logical deletion (BR7): the row is preserved, only the
// activation flag changes.
func (r *Repository) Deactivate(ctx context.Context, id string) error {
	tag, err := r.pool.Exec(ctx, "UPDATE services SET active = false WHERE id = $1", id)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrServiceNotFound
	}
	return nil
}
