-- =============================================================================
-- PostgreSQL schema — automotive-workshop-api
-- Generated from docs/entities.md
--
-- Conventions:
--   - snake_case for tables/columns.
--   - id UUID (technical key, generated via pgcrypto) as PRIMARY KEY.
--   - code BIGINT IDENTITY (human-readable sequential, shown to the user).
--   - created_at/updated_at on "registry" entities (not on event-trail tables,
--     which already carry the event's own occurred_at).
--
-- Run with: psql -f docs/schema.sql -d automotive_workshop
-- =============================================================================

-- ==== Extensions ====

CREATE EXTENSION IF NOT EXISTS "pgcrypto"; -- gen_random_uuid()
-- Optional: enable for fuzzy text search on name/license_plate (see GIN indexes below).
-- CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ==== Enums ====
-- We use native ENUM (not CHECK) because they are more compact on disk/index
-- and self-documenting. Cost: evolving values requires ALTER TYPE ... ADD VALUE.

DO $$ BEGIN
    CREATE TYPE product_type AS ENUM ('PART', 'SUPPLY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE customer_document_type AS ENUM ('CPF', 'CNPJ');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE customer_status AS ENUM ('ACTIVE', 'INACTIVE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- NOTE: the values of this enum are a deliberate exception to the "everything in
-- English" convention. ServiceOrder.status is kept in Portuguese by explicit
-- product decision (see docs/entities.md) — do not translate these values.
DO $$ BEGIN
    CREATE TYPE service_order_status AS ENUM (
        'RECEBIDA',
        'EM_DIAGNOSTICO',
        'AGUARDANDO_APROVACAO',
        'EM_EXECUCAO',
        'FINALIZADA',
        'ENTREGUE'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE quote_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE history_event AS ENUM ('creation', 'approval', 'completion', 'cancellation');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE audit_event AS ENUM ('start', 'end');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ==== Tables ====

-- ---- Customer ----

CREATE TABLE IF NOT EXISTS customers (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code          BIGINT GENERATED ALWAYS AS IDENTITY,
    name          TEXT NOT NULL,
    document      TEXT NOT NULL,
    document_type customer_document_type NOT NULL,
    phone         TEXT NOT NULL,
    email         TEXT,
    status        customer_status NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE customers IS 'Workshop customer, an individual or a company.';
COMMENT ON COLUMN customers.id IS 'Secure technical identifier, generated by the system.';
COMMENT ON COLUMN customers.code IS 'Human-readable/sequential identifier shown to the user (e.g. on screens, receipts, search).';
COMMENT ON COLUMN customers.name IS 'Full name or company name of the customer.';
COMMENT ON COLUMN customers.document IS 'CPF or CNPJ of the customer, always stored normalized (digits only), used for tax identification.';
COMMENT ON COLUMN customers.document_type IS 'Document kind: CPF (individual) or CNPJ (company), derived from the document at write time.';
COMMENT ON COLUMN customers.phone IS 'Main contact phone number.';
COMMENT ON COLUMN customers.email IS 'Contact e-mail, used for notifications and communication.';
COMMENT ON COLUMN customers.status IS 'Customer situation: ACTIVE or INACTIVE. Starts ACTIVE; moved to INACTIVE only via explicit deactivation (logical delete), never reactivated automatically.';
COMMENT ON COLUMN customers.created_at IS 'Record creation date/time, generated automatically.';
COMMENT ON COLUMN customers.updated_at IS 'Record last update date/time, generated automatically.';

-- ---- Vehicle ----

CREATE TABLE IF NOT EXISTS vehicles (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code           BIGINT GENERATED ALWAYS AS IDENTITY,
    license_plate  TEXT NOT NULL,
    brand          TEXT NOT NULL,
    model          TEXT NOT NULL,
    year           SMALLINT NOT NULL,
    color          TEXT NOT NULL,
    customer_id    UUID NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE vehicles IS 'Vehicle belonging to a customer.';
COMMENT ON COLUMN vehicles.id IS 'Secure technical identifier, generated by the system.';
COMMENT ON COLUMN vehicles.code IS 'Human-readable/sequential identifier shown to the user.';
COMMENT ON COLUMN vehicles.license_plate IS 'Vehicle license plate.';
COMMENT ON COLUMN vehicles.brand IS 'Vehicle manufacturer (e.g. Fiat, Volkswagen).';
COMMENT ON COLUMN vehicles.model IS 'Vehicle model (e.g. Uno, Gol).';
COMMENT ON COLUMN vehicles.year IS 'Vehicle manufacturing/model year.';
COMMENT ON COLUMN vehicles.color IS 'Vehicle predominant color.';
COMMENT ON COLUMN vehicles.customer_id IS 'Reference to the owning Customer.';
COMMENT ON COLUMN vehicles.created_at IS 'Record creation date/time, generated automatically.';
COMMENT ON COLUMN vehicles.updated_at IS 'Record last update date/time, generated automatically.';

-- ---- Product ----

CREATE TABLE IF NOT EXISTS products (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code           BIGINT GENERATED ALWAYS AS IDENTITY,
    name           TEXT NOT NULL,
    description    TEXT NOT NULL,
    unit_price     NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    current_stock  INTEGER NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    type           product_type NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE products IS 'Replacement part or consumable supply.';
COMMENT ON COLUMN products.id IS 'Secure technical identifier, generated by the system.';
COMMENT ON COLUMN products.code IS 'Human-readable/sequential identifier shown to the user.';
COMMENT ON COLUMN products.name IS 'Product name.';
COMMENT ON COLUMN products.description IS 'Detailed product description.';
COMMENT ON COLUMN products.unit_price IS 'Unit sale price of the product.';
COMMENT ON COLUMN products.current_stock IS 'Quantity currently available in stock at query time.';
COMMENT ON COLUMN products.type IS 'Product category: PART (replacement part) or SUPPLY (consumable material).';
COMMENT ON COLUMN products.created_at IS 'Record creation date/time, generated automatically.';
COMMENT ON COLUMN products.updated_at IS 'Record last update date/time, generated automatically.';

-- ---- Service ----

CREATE TABLE IF NOT EXISTS services (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code           BIGINT GENERATED ALWAYS AS IDENTITY,
    name           TEXT NOT NULL,
    description    TEXT NOT NULL,
    price          NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    estimated_time INTEGER CHECK (estimated_time IS NULL OR estimated_time > 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE services IS 'Service offered by the workshop (e.g. oil change, wheel alignment).';
COMMENT ON COLUMN services.id IS 'Secure technical identifier, generated by the system.';
COMMENT ON COLUMN services.code IS 'Human-readable/sequential identifier shown to the user.';
COMMENT ON COLUMN services.name IS 'Name of the offered service (e.g. oil change, wheel alignment).';
COMMENT ON COLUMN services.description IS 'Detailed description of what the service covers.';
COMMENT ON COLUMN services.price IS 'Price charged for performing the service.';
COMMENT ON COLUMN services.estimated_time IS 'Estimated execution time, in minutes. Optional field.';
COMMENT ON COLUMN services.created_at IS 'Record creation date/time, generated automatically.';
COMMENT ON COLUMN services.updated_at IS 'Record last update date/time, generated automatically.';

-- ---- ServiceOrder ----

CREATE TABLE IF NOT EXISTS service_orders (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code         BIGINT GENERATED ALWAYS AS IDENTITY,
    customer_id  UUID NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
    vehicle_id   UUID NOT NULL REFERENCES vehicles (id) ON DELETE RESTRICT,
    opened_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    status       service_order_status NOT NULL DEFAULT 'RECEBIDA',
    notes        TEXT NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE service_orders IS 'Service order opened for a vehicle/customer.';
COMMENT ON COLUMN service_orders.id IS 'Secure technical identifier, generated by the system.';
COMMENT ON COLUMN service_orders.code IS 'Human-readable/sequential identifier of the service order, used for lookup and communication with the customer.';
COMMENT ON COLUMN service_orders.customer_id IS 'Reference to the requesting Customer.';
COMMENT ON COLUMN service_orders.vehicle_id IS 'Reference to the Vehicle being serviced.';
COMMENT ON COLUMN service_orders.opened_at IS 'Date/time the service order was opened.';
COMMENT ON COLUMN service_orders.status IS 'RECEBIDA -> EM_DIAGNOSTICO -> AGUARDANDO_APROVACAO -> EM_EXECUCAO -> FINALIZADA -> ENTREGUE. Values intentionally kept in Portuguese (see docs/entities.md).';
COMMENT ON COLUMN service_orders.notes IS 'Free-form notes about the service (e.g. customer report, vehicle condition).';
COMMENT ON COLUMN service_orders.created_at IS 'Record creation date/time, generated automatically.';
COMMENT ON COLUMN service_orders.updated_at IS 'Record last update date/time, generated automatically.';
-- Note: the doc models ServiceOrder.quote <-> Quote.serviceOrderId as a circular
-- 1:1 reference. The physical FK lives only on quotes.service_order_id (UNIQUE),
-- avoiding two redundant FKs pointing at each other; a service order's quote is
-- obtained through that reverse index.

-- ---- Quote ----

CREATE TABLE IF NOT EXISTS quotes (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code              BIGINT GENERATED ALWAYS AS IDENTITY,
    service_order_id  UUID NOT NULL UNIQUE REFERENCES service_orders (id) ON DELETE CASCADE,
    total_amount      NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    status            quote_status NOT NULL DEFAULT 'PENDING',
    generated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    responded_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (responded_at IS NULL OR responded_at >= generated_at)
);

COMMENT ON TABLE quotes IS 'Quote linked 1:1 to a service order.';
COMMENT ON COLUMN quotes.id IS 'Secure technical identifier, generated by the system.';
COMMENT ON COLUMN quotes.code IS 'Human-readable/sequential identifier of the quote.';
COMMENT ON COLUMN quotes.service_order_id IS 'Reference to the ServiceOrder this quote belongs to.';
COMMENT ON COLUMN quotes.total_amount IS 'Total quote amount (sum of products and services).';
COMMENT ON COLUMN quotes.status IS 'Quote status: PENDING (awaiting customer response), APPROVED (customer accepted) or REJECTED (customer declined).';
COMMENT ON COLUMN quotes.generated_at IS 'Date/time the quote was generated and sent to the customer.';
COMMENT ON COLUMN quotes.responded_at IS 'Date/time the customer responded (approved/rejected). Optional, filled only after a response.';
COMMENT ON COLUMN quotes.created_at IS 'Record creation date/time, generated automatically.';
COMMENT ON COLUMN quotes.updated_at IS 'Record last update date/time, generated automatically.';

-- ---- Quote <-> Product / Service (N:N) ----
-- The doc models Quote.products/services as arrays; physically this becomes
-- join tables. applied_unit_price/applied_price snapshot the price at the time
-- of the quote, since the catalog price may change afterward.

CREATE TABLE IF NOT EXISTS quote_products (
    quote_id            UUID NOT NULL REFERENCES quotes (id) ON DELETE CASCADE,
    product_id          UUID NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    quantity            INTEGER NOT NULL CHECK (quantity > 0),
    applied_unit_price  NUMERIC(12, 2) NOT NULL CHECK (applied_unit_price >= 0),
    PRIMARY KEY (quote_id, product_id)
);

COMMENT ON TABLE quote_products IS 'Products/parts included in a quote, with the price applied at the time.';
COMMENT ON COLUMN quote_products.quote_id IS 'Reference to the Quote this item belongs to.';
COMMENT ON COLUMN quote_products.product_id IS 'Reference to the Product included in the quote.';
COMMENT ON COLUMN quote_products.quantity IS 'Quantity of the product included in the quote.';
COMMENT ON COLUMN quote_products.applied_unit_price IS 'Unit price of the product at the time it was included in the quote (snapshot).';

CREATE TABLE IF NOT EXISTS quote_services (
    quote_id       UUID NOT NULL REFERENCES quotes (id) ON DELETE CASCADE,
    service_id     UUID NOT NULL REFERENCES services (id) ON DELETE RESTRICT,
    applied_price  NUMERIC(12, 2) NOT NULL CHECK (applied_price >= 0),
    PRIMARY KEY (quote_id, service_id)
);

COMMENT ON TABLE quote_services IS 'Services included in a quote, with the price applied at the time.';
COMMENT ON COLUMN quote_services.quote_id IS 'Reference to the Quote this item belongs to.';
COMMENT ON COLUMN quote_services.service_id IS 'Reference to the Service included in the quote.';
COMMENT ON COLUMN quote_services.applied_price IS 'Price of the service at the time it was included in the quote (snapshot).';

-- ---- ServiceOrderHistory ----

CREATE TABLE IF NOT EXISTS service_order_history (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    service_order_id  UUID NOT NULL REFERENCES service_orders (id) ON DELETE CASCADE,
    occurred_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    event             history_event NOT NULL,
    description       TEXT NOT NULL,
    previous_status   service_order_status NOT NULL,
    new_status        service_order_status NOT NULL
);

COMMENT ON TABLE service_order_history IS 'Trail of events and status changes of a service order, for audit and traceability.';
COMMENT ON COLUMN service_order_history.id IS 'Technical identifier of the history record.';
COMMENT ON COLUMN service_order_history.service_order_id IS 'Reference to the ServiceOrder this event belongs to.';
COMMENT ON COLUMN service_order_history.occurred_at IS 'Date/time the event occurred.';
COMMENT ON COLUMN service_order_history.event IS 'Type of recorded event: creation, approval, completion or cancellation.';
COMMENT ON COLUMN service_order_history.description IS 'Details of what happened in the event.';
COMMENT ON COLUMN service_order_history.previous_status IS 'Service order status immediately before the event.';
COMMENT ON COLUMN service_order_history.new_status IS 'Service order status immediately after the event.';

-- ---- AuditServices ----

CREATE TABLE IF NOT EXISTS audit_services (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    service_order_id  UUID NOT NULL REFERENCES service_orders (id) ON DELETE CASCADE,
    service_id        UUID NOT NULL REFERENCES services (id) ON DELETE RESTRICT,
    occurred_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    event             audit_event NOT NULL
);

COMMENT ON TABLE audit_services IS 'Start and end of the execution of each service within a service order, for time/productivity tracking.';
COMMENT ON COLUMN audit_services.id IS 'Technical identifier of the audit record.';
COMMENT ON COLUMN audit_services.service_order_id IS 'Reference to the ServiceOrder in progress.';
COMMENT ON COLUMN audit_services.service_id IS 'Reference to the Service being executed.';
COMMENT ON COLUMN audit_services.occurred_at IS 'Date/time the event was recorded.';
COMMENT ON COLUMN audit_services.event IS 'Event milestone: start (execution started) or end (execution finished).';

-- =============================================================================
-- ==== Indexes ====
-- =============================================================================

-- ---- Human-readable codes (lookup by the number shown to the user) ----

CREATE UNIQUE INDEX IF NOT EXISTS ux_customers_code ON customers (code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_vehicles_code ON vehicles (code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_products_code ON products (code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_services_code ON services (code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_service_orders_code ON service_orders (code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_quotes_code ON quotes (code);

-- ---- Business uniqueness ----

CREATE UNIQUE INDEX IF NOT EXISTS ux_customers_document ON customers (document);
CREATE UNIQUE INDEX IF NOT EXISTS ux_vehicles_license_plate ON vehicles (license_plate);
-- Partial unique: e-mail is optional, but when present it cannot repeat.
CREATE UNIQUE INDEX IF NOT EXISTS ux_customers_email ON customers (email) WHERE email IS NOT NULL;

-- ---- Foreign keys (Postgres does not index FKs automatically) ----

CREATE INDEX IF NOT EXISTS ix_vehicles_customer_id ON vehicles (customer_id);
CREATE INDEX IF NOT EXISTS ix_service_orders_customer_id ON service_orders (customer_id);
CREATE INDEX IF NOT EXISTS ix_service_orders_vehicle_id ON service_orders (vehicle_id);
CREATE INDEX IF NOT EXISTS ix_quote_products_product_id ON quote_products (product_id);
CREATE INDEX IF NOT EXISTS ix_quote_services_service_id ON quote_services (service_id);
CREATE INDEX IF NOT EXISTS ix_service_order_history_service_order_id ON service_order_history (service_order_id);
CREATE INDEX IF NOT EXISTS ix_audit_services_service_order_id ON audit_services (service_order_id);
CREATE INDEX IF NOT EXISTS ix_audit_services_service_id ON audit_services (service_id);
-- quotes.service_order_id already has a unique index (UNIQUE above creates one).

-- ---- Frequent workshop queries ----

-- List of service orders by customer, most recent first.
CREATE INDEX IF NOT EXISTS ix_service_orders_customer_opened
    ON service_orders (customer_id, opened_at DESC);

-- "Which service orders are in progress" is the most common query on the
-- operations dashboard; the partial index keeps this subset small and fast,
-- ignoring service orders already completed/delivered (most of the history).
CREATE INDEX IF NOT EXISTS ix_service_orders_status_active
    ON service_orders (status, opened_at DESC)
    WHERE status NOT IN ('FINALIZADA', 'ENTREGUE');

-- Filter by product type (PART/SUPPLY) on catalog/stock screens.
CREATE INDEX IF NOT EXISTS ix_products_type ON products (type);

-- Restock alert: products with low stock.
CREATE INDEX IF NOT EXISTS ix_products_low_stock
    ON products (current_stock)
    WHERE current_stock < 10;

-- Quotes pending a customer response.
CREATE INDEX IF NOT EXISTS ix_quotes_status_pending
    ON quotes (status, generated_at DESC)
    WHERE status = 'PENDING';

-- Service execution audit by service order.
CREATE INDEX IF NOT EXISTS ix_audit_services_order_service
    ON audit_services (service_order_id, service_id, occurred_at);

-- ---- Text search (optional) ----
-- Requires the pg_trgm extension (commented out at the top of the file).
-- Speeds up ILIKE '%term%' searches on customer name and vehicle license plate.
-- CREATE INDEX IF NOT EXISTS ix_customers_name_trgm ON customers USING GIN (name gin_trgm_ops);
-- CREATE INDEX IF NOT EXISTS ix_vehicles_license_plate_trgm ON vehicles USING GIN (license_plate gin_trgm_ops);

-- =============================================================================
-- ==== updated_at utility trigger ====
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY['customers', 'vehicles', 'products', 'services', 'service_orders', 'quotes']
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_set_updated_at ON %I; '
            'CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION set_updated_at();',
            tbl, tbl
        );
    END LOOP;
END $$;
