package product

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// Type represents the category of product: PART or SUPPLY.
type Type string

const (
	TypePart   Type = "PART"
	TypeSupply Type = "SUPPLY"
)

// Status represents the operational state: ACTIVE or INACTIVE.
type Status string

const (
	StatusActive   Status = "ACTIVE"
	StatusInactive Status = "INACTIVE"
)

// MovementType represents stock adjustment direction: ENTRY or EXIT.
type MovementType string

const (
	MovementTypeEntry MovementType = "ENTRY"
	MovementTypeExit  MovementType = "EXIT"
)

// StockMovement represents an audit record for a stock balance change.
type StockMovement struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Type          MovementType
	Quantity      int
	PreviousStock int
	NewStock      int
	Reason        string
	CreatedAt     time.Time
}

// Product is the domain aggregate representing a part or supply in workshop catalog/stock.
type Product struct {
	ID           uuid.UUID
	Code         int64
	Name         string
	Description  string
	UnitPrice    float64
	CurrentStock int
	Type         Type
	Status       Status
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// ParseType validates and parses a string into a valid Product Type.
//
// Args:
//
//	rawType(string): raw string value representing the product type ("PART" or "SUPPLY")
//
// Returns:
//
//	productType(Type): parsed product type
//	err(error): validation error if invalid type
func ParseType(rawType string) (Type, error) {
	upper := strings.ToUpper(strings.TrimSpace(rawType))
	switch upper {
	case string(TypePart):
		return TypePart, nil
	case string(TypeSupply):
		return TypeSupply, nil
	default:
		return "", ErrInvalidType
	}
}

// ParseMovementType validates and parses a string into a MovementType (ENTRY or EXIT).
//
// Args:
//
//	rawType(string): raw string value ("ENTRY" or "EXIT")
//
// Returns:
//
//	movementType(MovementType): parsed movement type
//	err(error): validation error if invalid movement type
func ParseMovementType(rawType string) (MovementType, error) {
	upper := strings.ToUpper(strings.TrimSpace(rawType))
	switch upper {
	case string(MovementTypeEntry), "ENTRADA", "IN":
		return MovementTypeEntry, nil
	case string(MovementTypeExit), "SAIDA", "SAÍDA", "OUT":
		return MovementTypeExit, nil
	default:
		return "", ErrInvalidMovementType
	}
}

// NewProduct creates a new Product aggregate starting in ACTIVE status.
//
// Args:
//
//	code(*int64): optional manual code pointer (nil if autogenerated)
//	name(string): product display name
//	description(string): detailed product description
//	unitPrice(float64): unit sale price
//	currentStock(int): initial stock quantity
//	rawType(string): product type ("PART" or "SUPPLY")
//
// Returns:
//
//	product(*Product): initialized product domain instance
//	err(error): error if validation fails
func NewProduct(code *int64, name, description string, unitPrice float64, currentStock int, rawType string) (*Product, error) {
	trimmedName := strings.TrimSpace(name)
	if trimmedName == "" {
		return nil, fmt.Errorf("%w: name cannot be empty", ErrInvalidType)
	}

	if unitPrice < 0 {
		return nil, ErrInvalidUnitPrice
	}

	if currentStock < 0 {
		return nil, ErrInvalidStock
	}

	productType, err := ParseType(rawType)
	if err != nil {
		return nil, err
	}

	var productCode int64
	if code != nil {
		if *code <= 0 {
			return nil, fmt.Errorf("%w: code must be positive", ErrInvalidType)
		}
		productCode = *code
	}

	return &Product{
		ID:           uuid.New(),
		Code:         productCode,
		Name:         trimmedName,
		Description:  strings.TrimSpace(description),
		UnitPrice:    unitPrice,
		CurrentStock: currentStock,
		Type:         productType,
		Status:       StatusActive,
	}, nil
}

// Deactivate sets the product status to INACTIVE. It is idempotent.
//
// Args:
//
//	(none)
//
// Returns:
//
//	(none)
func (product *Product) Deactivate() {
	product.Status = StatusInactive
}

// IsActive checks if the product is currently ACTIVE.
//
// Args:
//
//	(none)
//
// Returns:
//
//	active(bool): true if status is ACTIVE
func (product *Product) IsActive() bool {
	return product.Status == StatusActive
}

// ApplyStockAdjustment validates and executes a stock adjustment on the Product aggregate.
//
// Args:
//
//	movementType(MovementType): ENTRY or EXIT
//	quantity(int): stock quantity change (> 0)
//	reason(string): justification text for stock movement
//
// Returns:
//
//	movement(*StockMovement): created movement record
//	err(error): error if validation or stock check fails
func (product *Product) ApplyStockAdjustment(movementType MovementType, quantity int, reason string) (*StockMovement, error) {
	if !product.IsActive() {
		return nil, ErrInactiveProduct
	}

	if quantity <= 0 {
		return nil, ErrInvalidQuantity
	}

	trimmedReason := strings.TrimSpace(reason)
	if trimmedReason == "" {
		return nil, ErrEmptyReason
	}

	previousStock := product.CurrentStock

	switch movementType {
	case MovementTypeEntry:
		product.CurrentStock += quantity
	case MovementTypeExit:
		if product.CurrentStock < quantity {
			return nil, ErrInsufficientStock
		}
		product.CurrentStock -= quantity
	default:
		return nil, ErrInvalidMovementType
	}

	return &StockMovement{
		ID:            uuid.New(),
		ProductID:     product.ID,
		Type:          movementType,
		Quantity:      quantity,
		PreviousStock: previousStock,
		NewStock:      product.CurrentStock,
		Reason:        trimmedReason,
		CreatedAt:     time.Now(),
	}, nil
}

// UpdateDetails updates cadastral information of the product (name, description, unitPrice, type).
// Direct stock updates are not allowed through this method (RNF07).
//
// Args:
//
//	name(*string): optional new name
//	description(*string): optional new description
//	unitPrice(*float64): optional new unit price
//	rawType(*string): optional new raw type
//
// Returns:
//
//	err(error): error if validation fails
func (product *Product) UpdateDetails(name, description *string, unitPrice *float64, rawType *string) error {
	if name != nil {
		trimmed := strings.TrimSpace(*name)
		if trimmed == "" {
			return fmt.Errorf("%w: name cannot be empty", ErrInvalidType)
		}
		product.Name = trimmed
	}

	if description != nil {
		product.Description = strings.TrimSpace(*description)
	}

	if unitPrice != nil {
		if *unitPrice < 0 {
			return ErrInvalidUnitPrice
		}
		product.UnitPrice = *unitPrice
	}

	if rawType != nil {
		parsedType, err := ParseType(*rawType)
		if err != nil {
			return err
		}
		product.Type = parsedType
	}

	return nil
}
