package product

import (
	"context"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProductService(t *testing.T) {
	ctx := context.Background()

	t.Run("Create product with autogenerated code", func(t *testing.T) {
		repo := newFakeRepository()
		service := NewProductService(repo)

		p, err := service.Create(ctx, nil, "Pastilha de Freio", "Pastilha dianteira", 120.00, 15, "PART")
		require.NoError(t, err)
		assert.NotEqual(t, uuid.Nil, p.ID)
		assert.Greater(t, p.Code, int64(0))
		assert.Equal(t, "Pastilha de Freio", p.Name)
	})

	t.Run("Create product with explicit code and duplicate check", func(t *testing.T) {
		repo := newFakeRepository()
		service := NewProductService(repo)

		code := int64(500)
		p1, err := service.Create(ctx, &code, "Vela de Ignição", "Vela iridium", 45.00, 30, "PART")
		require.NoError(t, err)
		assert.Equal(t, int64(500), p1.Code)

		_, err = service.Create(ctx, &code, "Outra Vela", "Vela simples", 25.00, 10, "PART")
		assert.ErrorIs(t, err, ErrDuplicateCode)
	})

	t.Run("Update product details and reject direct stock update", func(t *testing.T) {
		repo := newFakeRepository()
		service := NewProductService(repo)

		p, err := service.Create(ctx, nil, "Filtro de Ar", "Filtro motor", 50.00, 10, "PART")
		require.NoError(t, err)

		// Reject direct stock modification via update (RNF07)
		stockMod := 99
		_, err = service.Update(ctx, p.ID, UpdateInput{CurrentStock: &stockMod})
		assert.ErrorIs(t, err, ErrStockDirectUpdateNotAllowed)

		// Successful cadastral update
		newName := "Filtro de Ar Esportivo"
		newPrice := 65.00
		updated, err := service.Update(ctx, p.ID, UpdateInput{Name: &newName, UnitPrice: &newPrice})
		require.NoError(t, err)
		assert.Equal(t, "Filtro de Ar Esportivo", updated.Name)
		assert.Equal(t, 65.00, updated.UnitPrice)
		assert.Equal(t, 10, updated.CurrentStock) // stock untouched
	})

	t.Run("Deactivate product", func(t *testing.T) {
		repo := newFakeRepository()
		service := NewProductService(repo)

		p, err := service.Create(ctx, nil, "Fluido de Freio DOT4", "Fluido 500ml", 25.00, 5, "SUPPLY")
		require.NoError(t, err)

		deactivated, err := service.Deactivate(ctx, p.ID)
		require.NoError(t, err)
		assert.Equal(t, StatusInactive, deactivated.Status)
	})

	t.Run("Adjust stock entry and exit", func(t *testing.T) {
		repo := newFakeRepository()
		service := NewProductService(repo)

		p, err := service.Create(ctx, nil, "Amortecedor", "Traseiro", 150.00, 10, "PART")
		require.NoError(t, err)

		// Entry adjustment (+5)
		updated, m, err := service.AdjustStock(ctx, p.ID, "ENTRY", 5, "Compra de reposição")
		require.NoError(t, err)
		assert.Equal(t, 15, updated.CurrentStock)
		assert.Equal(t, 10, m.PreviousStock)
		assert.Equal(t, 15, m.NewStock)

		// Exit adjustment (-3)
		updatedExit, mExit, err := service.AdjustStock(ctx, p.ID, "EXIT", 3, "Uso em ordem de serviço")
		require.NoError(t, err)
		assert.Equal(t, 12, updatedExit.CurrentStock)
		assert.Equal(t, 15, mExit.PreviousStock)
		assert.Equal(t, 12, mExit.NewStock)
	})

	t.Run("Reject exit exceeding available stock", func(t *testing.T) {
		repo := newFakeRepository()
		service := NewProductService(repo)

		p, err := service.Create(ctx, nil, "Correia Dentada", "Correia", 80.00, 5, "PART")
		require.NoError(t, err)

		_, _, err = service.AdjustStock(ctx, p.ID, "EXIT", 10, "Saída excessiva")
		assert.ErrorIs(t, err, ErrInsufficientStock)

		balance, err := service.GetStockBalance(ctx, p.ID)
		require.NoError(t, err)
		assert.Equal(t, 5, balance.CurrentStock)
	})
}
